### ISSUE TITLE
Duration support

### ISSUE THREAD

**Issue by LeslieMurphy** [donbeave/graphql-java-datetime#26]
What do you think about adding support for ISO 8601 duration?

**Comment by donbeave** [comment]
It will be nice. Can you make a PR?

**Comment by LeslieMurphy** [comment]
I can try!

**Comment by LeslieMurphy** [comment]
Hi there.  I tried to get started on this and hit a blocker with OpenJdk14.  build.sh works fine.  test.sh fails with error messages.   Running test.sh  with OpenJdk12 works OK.  Not sure if this is a bug in your build stack or some Groovy / JDK issue?

 
Task :graphql-datetime-sample-app:compileTestGroovy FAILED
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
        at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)

...

Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.parseGroovyVersion(ApiGroovyCompiler.java:324)
        at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:167)

**Comment by donbeave** [comment]
Hi, @LeslieMurphy! It's Groovy's issue. Need to upgrade the Groovy and Spock version. I'm planning a switch to Kotlin for tests. Please use OpenJDK 12 or 8 for now.

**Comment by donbeave** [comment]
@LeslieMurphy thank you for this PR: https://github.com/donbeave/graphql-java-datetime/pull/29, since it's merged to the master branch, I'll close this ticket too. Duration support available in the 2.3.0 release version.
